/**
 * Maps lowercased country names and ISO codes to ISO 3166-1 alpha-2 codes.
 * Covers African countries and major world nations.
 */
export const COUNTRY_MAP: Record<string, string> = {
  // ISO codes (self-mapping)
  ng: 'NG',
  gh: 'GH',
  ke: 'KE',
  za: 'ZA',
  ug: 'UG',
  tz: 'TZ',
  et: 'ET',
  eg: 'EG',
  ao: 'AO',
  cm: 'CM',
  ci: 'CI',
  sn: 'SN',
  bj: 'BJ',
  tg: 'TG',
  rw: 'RW',
  zm: 'ZM',
  zw: 'ZW',
  mz: 'MZ',
  mg: 'MG',
  sd: 'SD',
  lr: 'LR',
  sl: 'SL',
  gn: 'GN',
  ne: 'NE',
  ml: 'ML',
  bf: 'BF',
  dz: 'DZ',
  ma: 'MA',
  tn: 'TN',
  ly: 'LY',
  us: 'US',
  gb: 'GB',
  ca: 'CA',
  au: 'AU',
  de: 'DE',
  fr: 'FR',
  br: 'BR',
  in: 'IN',
  cn: 'CN',
  jp: 'JP',
  // Country names
  nigeria: 'NG',
  nigerian: 'NG',
  ghana: 'GH',
  ghanaian: 'GH',
  kenya: 'KE',
  kenyan: 'KE',
  'south africa': 'ZA',
  'south african': 'ZA',
  uganda: 'UG',
  ugandan: 'UG',
  tanzania: 'TZ',
  tanzanian: 'TZ',
  ethiopia: 'ET',
  ethiopian: 'ET',
  egypt: 'EG',
  egyptian: 'EG',
  angola: 'AO',
  angolan: 'AO',
  cameroon: 'CM',
  cameroonian: 'CM',
  "ivory coast": 'CI',
  "côte d'ivoire": 'CI',
  senegal: 'SN',
  senegalese: 'SN',
  benin: 'BJ',
  togo: 'TG',
  togolese: 'TG',
  rwanda: 'RW',
  rwandan: 'RW',
  zambia: 'ZM',
  zambian: 'ZM',
  zimbabwe: 'ZW',
  zimbabwean: 'ZW',
  mozambique: 'MZ',
  mozambican: 'MZ',
  madagascar: 'MG',
  sudan: 'SD',
  sudanese: 'SD',
  liberia: 'LR',
  liberian: 'LR',
  'sierra leone': 'SL',
  guinea: 'GN',
  guinean: 'GN',
  niger: 'NE',
  mali: 'ML',
  malian: 'ML',
  'burkina faso': 'BF',
  algeria: 'DZ',
  algerian: 'DZ',
  morocco: 'MA',
  moroccan: 'MA',
  tunisia: 'TN',
  tunisian: 'TN',
  libya: 'LY',
  libyan: 'LY',
  'united states': 'US',
  american: 'US',
  america: 'US',
  'united kingdom': 'GB',
  britain: 'GB',
  british: 'GB',
  england: 'GB',
  canada: 'CA',
  canadian: 'CA',
  australia: 'AU',
  australian: 'AU',
  germany: 'DE',
  german: 'DE',
  france: 'FR',
  french: 'FR',
  brazil: 'BR',
  brazilian: 'BR',
  india: 'IN',
  indian: 'IN',
  china: 'CN',
  chinese: 'CN',
  japan: 'JP',
  japanese: 'JP',
};
